import { Booking } from '../types';
import { API_BASE_URL } from './apiClient';

export interface InvoiceItem {
  description: string;
  quantity: number;
  rate: number;
  amount: number;
}

export interface InvoiceData {
  invoiceNumber: string;
  invoiceDate: string;
  bookingId: string;
  customerName: string;
  customerEmail: string;
  customerPhone?: string;
  tripTitle: string;
  destination: string;
  travelDate: string;
  travellersCount: number;
  items: InvoiceItem[];
  subtotal: number;
  discount: number;
  taxes: number;
  totalAmount: number;
  paymentStatus: string;
  paymentMethod: string;
  companyName: string;
  companyGstin: string;
  companyAddress: string;
}

export const invoiceService = {
  generateInvoiceData(booking: Booking): InvoiceData {
    const bookingRef = booking.bookingId || booking.id;
    const invNumber = `INV-${bookingRef.replace(/^SKY-/, '')}`;
    const leadName = booking.primaryTraveller?.name || booking.leadGuest?.name || 'Valued Yatri';
    const leadEmail = booking.primaryTraveller?.email || booking.leadGuest?.email || 'yatri@sukhyatri.in';
    const leadPhone = booking.primaryTraveller?.phone || booking.leadGuest?.phone;

    const pricePerPerson = Math.round(booking.baseAmount / (booking.travellers || 1));

    const items: InvoiceItem[] = [
      {
        description: `${booking.packageTitle} — Base Tour Fare (SAC: 998555)`,
        quantity: booking.travellers || 1,
        rate: pricePerPerson,
        amount: booking.baseAmount,
      },
    ];

    if (booking.addonsAmount && booking.addonsAmount > 0) {
      items.push({
        description: 'Curated Experiences & Tour Enhancements',
        quantity: 1,
        rate: booking.addonsAmount,
        amount: booking.addonsAmount,
      });
    }

    if (booking.roomUpgradeAmount && booking.roomUpgradeAmount > 0) {
      items.push({
        description: `Accommodation Tier Upgrade (${booking.roomCategory || 'Luxury'})`,
        quantity: booking.rooms || 1,
        rate: booking.roomUpgradeAmount,
        amount: booking.roomUpgradeAmount,
      });
    }

    return {
      invoiceNumber: invNumber,
      invoiceDate: booking.createdAt || new Date().toISOString().split('T')[0],
      bookingId: bookingRef,
      customerName: leadName,
      customerEmail: leadEmail,
      customerPhone: leadPhone,
      tripTitle: booking.packageTitle,
      destination: booking.destination || booking.destName,
      travelDate: booking.travelDate,
      travellersCount: booking.travellers,
      items,
      subtotal: booking.baseAmount + (booking.addonsAmount || 0) + (booking.roomUpgradeAmount || 0),
      discount: booking.discountAmount || 0,
      taxes: booking.taxAmount || 0,
      totalAmount: booking.totalAmount,
      paymentStatus: (booking.paymentStatus || 'Paid').toUpperCase(),
      paymentMethod: (booking.paymentMethod || 'UPI').toUpperCase(),
      companyName: 'SukhYatri Private Limited',
      companyGstin: '32AABCS1429B1Z8',
      companyAddress: 'Fort Kochi Heritage Hub, Kochi, Kerala · New Delhi · Bengaluru',
    };
  },

  printInvoice(): void {
    if (typeof window !== 'undefined') {
      window.print();
    }
  },

  /**
   * Downloads official PDF invoice generated by backend server
   */
  async downloadInvoicePdf(bookingId: string): Promise<void> {
    const cleanId = bookingId.trim().toUpperCase();
    const token = typeof window !== 'undefined' ? localStorage.getItem('sukhyatri_auth_token') : null;
    const url = `${API_BASE_URL}/bookings/${cleanId}/invoice`;

    try {
      const response = await fetch(url, {
        method: 'GET',
        headers: {
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
      });

      if (!response.ok) {
        let errorMsg = 'Failed to download invoice';
        try {
          const errData = await response.json();
          errorMsg = errData.message || errorMsg;
        } catch {
          // not json
        }
        throw new Error(errorMsg);
      }

      const blob = await response.blob();
      const blobUrl = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = blobUrl;
      link.download = `SukhYatri_Invoice_${cleanId}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(blobUrl);
    } catch (err: any) {
      console.warn('[InvoiceService] Direct PDF download failed, falling back to print view:', err.message);
      // Fallback
      if (typeof window !== 'undefined') {
        window.print();
      }
      throw err;
    }
  },
};
